Traceback (most recent call last):
  File "/Users/adzcai/micromamba/envs/rlbook/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/adzcai/micromamba/envs/rlbook/lib/python3.11/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adzcai/micromamba/envs/rlbook/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adzcai/micromamba/envs/rlbook/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/adzcai/micromamba/envs/rlbook/lib/python3.11/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Users/adzcai/micromamba/envs/rlbook/lib/python3.11/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/adzcai/micromamba/envs/rlbook/lib/python3.11/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
def trajectory_log_likelihood(
    mdp: MDP,
    Ï„: Trajectory,
    Ï€: Float[Array, "S A"],
) -> float:
    """Compute the log-likelihood of a trajectory under a given MDP and policy."""
    total = jnp.log(mdp.Î¼[Ï„[0].s])
    total += jnp.log(Ï€[Ï„[0].s, Ï„[0].a])
    for i in range(1, mdp.H):
        total += jnp.log(mdp.P[Ï„[i - 1].s, Ï„[i - 1].a, Ï„[i].s])
        total += jnp.log(Ï€[Ï„[i].s, Ï„[i].a])
    return total
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[6], line 3[0m
[1;32m      1[0m [38;5;28;01mdef[39;00m [38;5;21mtrajectory_log_likelihood[39m(
[1;32m      2[0m     mdp: MDP,
[0;32m----> 3[0m     Ï„: [43mTrajectory[49m,
[1;32m      4[0m     Ï€: Float[Array, [38;5;124m"[39m[38;5;124mS A[39m[38;5;124m"[39m],
[1;32m      5[0m ) [38;5;241m-[39m[38;5;241m>[39m [38;5;28mfloat[39m:
[1;32m      6[0m [38;5;250m    [39m[38;5;124;03m"""Compute the log-likelihood of a trajectory under a given MDP and policy."""[39;00m
[1;32m      7[0m     total [38;5;241m=[39m jnp[38;5;241m.[39mlog(mdp[38;5;241m.[39mÎ¼[Ï„[[38;5;241m0[39m][38;5;241m.[39ms])

[0;31mNameError[0m: name 'Trajectory' is not defined

